imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
twig:
    globals: 
        perfilEst:   %perfilEst%
        perfilDoc:   %perfilDoc%
        perfilAdmin: %perfilAdmin%
        perfilEstDoc: %perfilEstDoc%
        perfilEstAdm: %perfilEstAdm%
        perfilDocAdm: %perfilDocAdm%
        perfilCordi: %perfilCordi%
        perfilEstCordi: %perfilEstCordi%
        perfilDocCordi: %perfilDocCordi%
        ReporteEstudiantePorCarrera: %ReporteEstudiantePorCarrera%
        ReporteInscritosMatriculados: %ReporteInscritosMatriculados%
        ReporteMateriasAprobada: %ReporteMateriasAprobada%
        ConsultaEstudiantesMateriaParalelo: %ConsultaEstudiantesMateriaParalelo%
        AprobacionInscripcion: %AprobacionInscripcion%
        LegalizacionOrdenPago: %LegalizacionOrdenPago%
        AnulacionMateria: %AnulacionMateria%
        GeneracionCalendarioAcademico: %GeneracionCalendarioAcademico%
        GeneracionHorariosClases: %GeneracionHorariosClases%
        GeneracionHorariosExamen: %GeneracionHorariosExamen%
        SubirSolicitudes: %SubirSolicitudes%
        ConsultaHorariosClases: %ConsultaHorariosClases%
        ConsultaHorariosExamen: %ConsultaHorariosExamen%
        ConsultaHorariosClasesPersonalizados: %ConsultaHorariosClasesPersonalizados%
        ConsultaHorariosExamenPersonalizados: %ConsultaHorariosExamenPersonalizados%