admin_academico_home:
    path:     /calendario
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:calendario_carrera }
admin_academico_cambio_pass:
    path:     /restablecer_pass
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:cambio_password }
admin_academico_ingreso_nuevo_pass:
    path:     /nuevo_pass
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:ingreso_nuevo_pass }
admin_academico_cargar_eventos:
    path:     /cargar_eventos
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:cargar_eventos }
admin_academico_cargar_eventos_user:
    path:     /calendario_usuarios
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:cargar_eventos_carrera_user }
admin_registro_ordenpago:
    path:     /registroordenpago
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:registroordenpago }
admin_carreras_ordenpago:
    path:     /carrerasordenpago
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:carrerasordenpago }
admin_listar_ordenpago:
    path:     /listarordenpago
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:listarordenpago }
admin_actualiza_ordenpago:
    path:     /actualizaordenpago
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:actualizaordenpago }
    # path:     /eventos_user
    # defaults: { _controller: TitulacionSisAcademicoBundle:Admin:cargar_eventos_carrera_user }
admin_academico_crear_eventos:
    path:     /crear_evento
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:crear_eventos_academicos }
admin_academico_insertar_eventos:
    path:     /insertar_evento
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:insertar_eventos_calendario }
admin_academico_editar_eventos:
    path:     /editar_evento
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:editar_eventos_calendario }
admin_academico_modificar_eventos:
    path:     /modificar_evento
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:modificar_eventos_calendario }
