admin_academico_home:
    path:     /calendario
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:calendario_carrera }
admin_academico_cambio_pass:
    path:     restablecer_pass
    defaults: { _controller: TitulacionSisAcademicoBundle:Admin:cambio_password }