SisAcademico_Estudiantes_home:
    path:     /
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:index }

estudiantes_notas_actuales:
    pattern:  /index
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:index}

estudiantes_matriculacion:
    pattern:  /matriculacion
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:Matriculacion}

estudiantes_deudas:
    pattern:  /deudas
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:Deudas}

estudiantes_notas_historico:
    pattern:  /historico
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:listarmaterias}
estudiantes_menu_derecho:
    pattern:  /menuderecho
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:menuderecho}
estudiantes_anulacion:
    pattern:  /anulacion
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:anulacion_materias}
estudiantes_anulacion_materias:
    pattern:  /anulacion_materias
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:anulacion_materias_2}
estudiantes_anulacion_materias_2:
    pattern:  /anulacion_materias_2
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:anulacion_materias_3}
estudiantes_proceso_matricula:
    pattern:  /procesomatricula
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:procesomatricula}
estudiantes_grabar_matricula:
    pattern:  /grabarmatricula
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:estudiantes_grabar_matricula}
estudiantes_presenta_matricula:
    pattern:  /presentarmatricula
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:presenta_matricula}
estudiantes_pdf_matricula:
    pattern:  /pdfmatricula/{idEstudiante}/{idCarrera}/{ciclo}/{carrera}
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:pdfmatricula}
estudiantes_genera_turno:
    pattern:  /generaturno
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:generaturno}
estudiantes_pdf_ordenpago:
    pattern:  /pdfordenpago/{idEstudiante}/{idCarrera}/{ciclo}/{carrera}
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:pdfordenpago}
estudiantes_subir_archivos:
    pattern:  /subirarchivos/{idEstudiante}
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:subirarchivos}  
estudiantes_pdf_anulamateria:
    pattern:  /pdfAnulacionMaterias/{idEstudiante}/{idCarrera}/{ciclo}/{carrera}
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:pdfAnulacionMaterias}    
estudiantes_pdf_horarioexamen:
    pattern:  /pdfHorarioExamen/{idEstudiante}/{idCarrera}/{ciclo}/{carrera}
    defaults: { _controller: TitulacionSisAcademicoBundle:Estudiantes:pdfHorarioExamen}
SisAcademico_docentes:
    resource: "@TitulacionSisAcademicoBundle/Resources/config/docentes.yml"
    prefix:   /docentes
