notificaciones_index:
    path:     /
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:index_notificaciones }

notificaciones_mensajes:
    path:     /Mensajes
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:mensajes_universidad }
    
notificaciones_eventos:
    path:     /Eventos
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:eventos_universidad }
    
notificaciones_notificaciones:
    path:     /Notificaciones
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:notificaciones_universidad }
    
notificaciones_Lectura:
    path:     /Lectura
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:Lectura }

