dayscript_index:
    path:     /
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:index_notificaciones }

dayscript_mensajes:
    path:     /Mensajes
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:mensajes_universidad }
    
dayscript_eventos:
    path:     /Eventos
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:eventos_universidad }
    
dayscript_notificaciones:
    path:     /Notificaciones
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:notificaciones_universidad }
    
dayscript_configuracion:
    path:     /Configuracion
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:perfil }

dayscript_CambioContraseña:
    path:     /Clave
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:password }

dayscript_Sugerencia:
    path:     /Sugerencia
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:sugerencia }
    
dayscript_Lectura:
    path:     /Lectura
    defaults: { _controller: TitulacionSisAcademicoBundle:Notificaciones:Lectura }

